# Generated by Django 3.2.6 on 2021-08-06 15:32

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points',  ArrayField(ArrayField(models.DecimalField(max_digits = 10, decimal_places = 2),size=2,),size=4,)),
            ],
        ),
    ]
